### ISSUE TITLE
Some podcasts get downloaded to the main folder

### ISSUE THREAD

**Issue by TheFrenchGhosty** [akhilrex/podgrab#152]
- Installation Type: [Docker/Native] Docker
 - Have you tried using the latest docker image / code base [yes/no]: I'm already using :latest

**Describe the bug**

Some podcasts get downloaded to their folder (all episodes) + to the "main" library (almost all episodes) for seemingly no reason.

**To Reproduce**

Feeds causing this problem:

https://latenightlinux.com/feed/mp3

https://latenightlinux.com/feed/extra

**Expected behavior**
They only get downloaded to their folder.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by akhilrex** [comment]
I am not able to replicate this issue. The files are staying in their respective folders only.

Are you sure you don't have any other applications/scripts doing something else?

**Comment by TheFrenchGhosty** [comment]
Nope, Podgrab is the only thing writing to the folder.

I really have no idea what's the issue.

**Comment by TheFrenchGhosty** [comment]
@akhilrex Here is a tree of the issue:

**Comment by akhilrex** [comment]
Can you please share your docker-compose file?

**Comment by TheFrenchGhosty** [comment]
@akhilrex 

```
version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
      - PASSWORD=[REDACTED]
    volumes:
      - /path/to/podgrab/config:/config
      - /path/to/Podcasts:/assets
    ports:
      - 127.0.0.1:9045:8080
    restart: unless-stopped
```
