### ISSUE TITLE
[Feature Request] Allow the Setting of GUID / PUID on Docker Container

### ISSUE THREAD

**Issue by adammckay** [akhilrex/podgrab#16]
Sorry, I didn't know where to post on Docker Hub but I know this is the code repo...  here goes...

It would be nice if the Docker container allowed the setting of GUID / PUID in the environment variables (similar to all images produced by LinuxServer.io images.  As it stands now, the Docker container downloads all files as root:root and then I must constantly chown the entire folder to work with it.

Thanks for your consideration.

**Comment by spencerhughes** [comment]
#18

**Comment by ksurl** [comment]
you can also use `-u` in docker run or `user: ` in compose with the corresponding gid:uid

**Comment by undaunt** [comment]
@adammckay I too was familiar with how Linuxserver does it, but here is my compose and it's working excellently with the native docker features, as @ksurl mentioned.

```
# Podgrab - Podcast Downloader
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    restart: unless-stopped
    networks:
      - $TRAEFIK_NETWORK
    security_opt:
      - no-new-privileges
    user: "1000:1000"
    volumes:
      - ${DOCKERDIR}/podgrab:/config
      - ${MEDIADIR}/podcasts:/assets
    environment:
      - CHECK_FREQUENCY=60
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.podgrab-rtr.entrypoints=https"
      - "traefik.http.routers.podgrab-rtr.rule=Host(`pod.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.podgrab-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.podgrab-rtr.service=podgrab-svc"
      - "traefik.http.services.podgrab-svc.loadbalancer.server.port=8080"
```
