### ISSUE TITLE
Docker update without losing config?

### ISSUE THREAD

**Issue by Thomas-O** [akhilrex/podgrab#254]
Hello,

I'm using Podgrab v2022.04.25. How can I update the Podgrab docker without losing the config and assets?

I see a backup option in the settings, but I'm not sure how to restore from a downloaded backup.

Thanks for your time and your help.

**Comment by SamTV12345** [comment]
I use this configuration:

```yaml
version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - /path/to/config:/config
      - /path/to/data:/assets
    ports:
      - 80:8080
    restart: unless-stopped
```
