### ISSUE TITLE
New repository https://github.com/SamTV12345/podgrabv2

### ISSUE THREAD

**Issue by SamTV12345** [akhilrex/podgrab#272]
I created a new [repository](https://github.com/SamTV12345/podgrabv2) that basically contains all features from this repo. Feel free to contribute. I will review prs as fast as possible.

**Comment by Morethanevil** [comment]
Every time I start your container, I get this error:

```
Attaching to podfetch-podgrabv2-1
podfetch-podgrabv2-1  | thread 'main' panicked at 'sqlite::/./db/podcast.db: NotPresent', src/config/dbconfig.rs:8:49
podfetch-podgrabv2-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
podfetch-podgrabv2-1 exited with code 101
```


This is my docker-compose.yml

```
version: '3'
services:
  podgrabv2:
    image: samuel19982/podgrabv2:latest
    ports:
      - "9514:8000"
    volumes:
      - /medien/podcast:/app/podcasts
      - /docker/podfetch/podfetch.db:/app/podcast.db
    environment:
      - POLLING_INTERVAL=240
      - SERVER_URL=http://localhost
```

I tried to start with a fresh directory for podfetch and I tried to copy over to old DB from podgrab. Nothing worked for me

I tried to open an issue in your repository, but it needs to much information, I use docker, not npm
